### ISSUE TITLE
Certain classes of Exceptions should halt execution rather than just logging the error

### ISSUE THREAD

**Issue by arik-shurygin** [CDCgov/cfa_azure#146]
There are certain exceptions within `cfa_azure` that are severe enough that they should immediately halt execution. Currently we just log the error and move forward.

For example, if an incorrect path to the configuration file is passed to the AzureClient, the following block of code will execute but not halt the program:

https://github.com/CDCgov/cfa_azure/blob/a7467d61dfdb58e35ee718fb475a27fe19cab289/cfa_azure/helpers.py#L32-L58

This code will carry on without a configuration toml and eventually error with an unrelated exception further down the program:

```
(mechanistic-model-py3.10) AH20@AZ1CFA1VSWP-124:~/scenmod-work/2024-10-02-docker-build-fix (docker-build-fix)$ python ./src/mechanistic_azure/experiment_launcher_azure.py --job_id 2024-10-02-ah20-docker-build-fix-1 --experiment_name example_azure_experiment
Traceback (most recent call last):
  File "/home/AH20/scenmod-work/2024-10-02-docker-build-fix/./src/mechanistic_azure/experiment_launcher_azure.py", line 37, in <module>
    launcher = AzureExperimentLauncher(
  File "/home/AH20/scenmod-work/2024-10-02-docker-build-fix/src/mechanistic_azure/azure_utilities.py", line 52, in __init__
    self._setup_azure_client(path_to_dockerfile)
  File "/home/AH20/scenmod-work/2024-10-02-docker-build-fix/src/mechanistic_azure/azure_utilities.py", line 177, in _setup_azure_client
    azure_client = AzureClient(config_path=self.azure_config_toml)
  File "/home/AH20/scenmod-work/2024-10-02-docker-build-fix/.venv/lib/python3.10/site-packages/cfa_azure/clients.py", line 43, in __init__
    helpers.check_config_req(self.config)
  File "/home/AH20/scenmod-work/2024-10-02-docker-build-fix/.venv/lib/python3.10/site-packages/cfa_azure/helpers.py", line 1778, in check_config_req
    loaded = set(pd.json_normalize(config).columns)
  File "/home/AH20/scenmod-work/2024-10-02-docker-build-fix/.venv/lib/python3.10/site-packages/pandas/io/json/_normalize.py", line 445, in json_normalize
    raise NotImplementedError
NotImplementedError
```
I think this is a problem with more than just the loading of configuration tomls, in general it would be nice if `cfa_azure` had its own exception class where you could wrap critical exceptions within it to indicate a failure of some sort and add specific contextual information for the user.

**Comment by arik-shurygin** [comment]
@edbaskerville
